services:
  api:
    build: .
    container_name: conecta_atende_api
    ports:
      - "5005:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings__DefaultConnection=Server=db;Database=ConectaAtendeDB;User=sa;Password=SenhaForte123!;TrustServerCertificate=True;Encrypt=False;"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: conecta_atende_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: